/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  FetchHelperWebComponent as FetchHelper
} from './components/fetch-helper/fetch-helper';

declare global {
  interface HTMLFetchHelperElement extends FetchHelper, HTMLElement {
  }
  var HTMLFetchHelperElement: {
    prototype: HTMLFetchHelperElement;
    new (): HTMLFetchHelperElement;
  };
  interface HTMLElementTagNameMap {
    "fetch-helper": HTMLFetchHelperElement;
  }
  interface ElementTagNameMap {
    "fetch-helper": HTMLFetchHelperElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fetch-helper": JSXElements.FetchHelperAttributes;
    }
  }
  namespace JSXElements {
    export interface FetchHelperAttributes extends HTMLAttributes {
      selector?: string;
    }
  }
}

